application:
  name: thrnaxz
  project: thrnaxz
  publicly_accessible: true
databases:
- type: postgresql
  version: "12"
  name: my-psql
routers:
- name: main
  routes:
  - application_name: thrnaxz
    paths:
    - /
